import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { dashboardHomeForRole } from "@/lib/auth/roles";
import type { UserRole, SchoolType } from "@/types";
import { SCHOOL_TYPE_LABELS, SCHOOL_TYPE_ICONS } from "@/types";

export const revalidate = 0;

const schoolTypes: Array<{type:SchoolType;accent:string;description:string;levels:string[]}> = [
 {type:"primaire",accent:"from-cyan-400 to-blue-600",description:"Les premiers apprentissages avec un suivi simple et bienveillant.",levels:["Maternelle","CP1","CP2","CE1","CE2","CM1","CM2"]},
 {type:"college",accent:"from-blue-500 to-indigo-700",description:"Classes, matières, présences et résultats réunis au même endroit.",levels:["6ème","5ème","4ème","3ème"]},
 {type:"lycee",accent:"from-indigo-500 to-violet-700",description:"Un pilotage clair pour les filières et la préparation au bac.",levels:["Seconde","Première","Terminale"]},
 {type:"professionnel",accent:"from-violet-500 to-fuchsia-600",description:"Formations techniques, professionnelles et alternance sans complexité.",levels:["CAP","BEP","Bac Pro","BTS"]},
 {type:"islamique",accent:"from-emerald-400 to-teal-600",description:"Enseignement coranique, arabe et sciences islamiques structurés.",levels:["Coran","Arabe","Fiqh","Hadith"]}
];
const features = [["students","Élèves","Centralisez les dossiers et le suivi de chaque élève."],["teachers","Enseignants","Affectations, classes, matières et suivi pédagogique."],["grades","Notes & bulletins","Saisissez les résultats et facilitez les bulletins."],["attendance","Présences","Suivez présences, absences et retards rapidement."],["messages","Communication","Gardez l'école, les parents et les élèves connectés."],["calendar","Emplois du temps","Organisez les journées avec une vue claire et pratique."]] as const;
const spaces = [["admin","Administration","Pilotez l'établissement, les équipes, les classes et les paiements."],["teacher","Enseignants","Retrouvez classes, présences, notes et élèves à risque."],["student","Élèves","Consultez notes, emploi du temps, annonces et informations."],["parent","Parents","Suivez simplement la scolarité et les informations de votre enfant."]] as const;

export default async function HomePage(){
 let user=null; let dashboardHref="/auth";
 try{const supabase=await createClient();const {data:{user:currentUser}}=await supabase.auth.getUser();user=currentUser;if(currentUser){const {data:profile}=await supabase.from("profiles").select("role").eq("id",currentUser.id).maybeSingle();dashboardHref=dashboardHomeForRole((profile?.role as UserRole|undefined)??"parent");}}catch{}
 const primaryHref=user?dashboardHref:"/auth";
 return <>
  <section className="relative isolate min-h-[680px] overflow-hidden bg-[#f5fbff]">
   <div className="absolute inset-y-0 right-0 hidden w-[62%] bg-gradient-to-br from-[#0b57d0] via-[#0878df] to-[#27d7e8] lg:block schooly-wave"/>
   <div className="absolute -left-28 top-24 h-72 w-72 rounded-full bg-cyan-100/70 blur-3xl"/>
   <div className="relative mx-auto grid max-w-7xl items-center gap-8 px-4 pb-20 pt-14 sm:px-6 lg:min-h-[680px] lg:grid-cols-[.86fr_1.14fr] lg:px-8">
    <div className="relative z-10 max-w-xl"><span className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-4 py-2 text-[11px] font-black tracking-[.16em] text-blue-700"><span className="h-2 w-2 rounded-full bg-cyan-400"/>PLATEFORME ÉDUCATIVE</span><h1 className="mt-6 text-5xl font-black leading-[.98] tracking-[-.045em] text-slate-950 sm:text-6xl lg:text-[4.7rem]">L'école devient<br/><span className="text-blue-700">plus simple.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-600 sm:text-lg">Schooly réunit la gestion de l'établissement, les enseignants, les élèves et les parents dans une expérience moderne, claire et connectée.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={primaryHref} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-full bg-blue-700 px-7 font-black text-white shadow-xl shadow-blue-700/25 transition hover:-translate-y-1 hover:bg-blue-800">{user?"Mon espace":"Commencer"}<Arrow/></Link><Link href="#fonctionnalites" className="inline-flex min-h-13 items-center justify-center rounded-full border border-slate-200 bg-white px-7 font-bold text-slate-700 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:text-blue-700">Découvrir Schooly</Link></div><div className="mt-8 flex flex-wrap gap-5 text-xs font-bold text-slate-500"><span>✓ Simple</span><span>✓ Sécurisé</span><span>✓ Pensé pour les écoles</span></div></div>
    <div className="relative z-10 min-h-[420px] lg:min-h-[560px]"><HeroScene/></div>
   </div>
   <div className="absolute bottom-[-1px] left-0 right-0 h-20 bg-white [clip-path:ellipse(65%_75%_at_18%_100%)] lg:h-28 lg:[clip-path:ellipse(56%_75%_at_16%_100%)]"/>
  </section>
  <section className="relative z-20 -mt-4 px-4 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-3 rounded-[2rem] border border-slate-100 bg-white p-3 shadow-[0_24px_70px_rgba(15,23,42,.12)] sm:grid-cols-3 lg:grid-cols-5 lg:gap-0"><Stat value="98%" label="Satisfaction" icon="★"/><Stat value="6+" label="Niveaux scolaires" icon="⌁"/><Stat value="15:1" label="Suivi pédagogique" icon="◉"/><Stat value="30+" label="Fonctionnalités" icon="◆"/><Stat value="500+" label="Élèves suivis" icon="♧"/></div></section>
  <section id="etablissements" className="section-shell"><SectionTitle eyebrow="UNE SOLUTION POUR TOUS" title={<>Votre établissement, <span className="text-blue-700">votre façon</span> de gérer.</>} text="Une expérience Schooly qui s'adapte aux réalités de chaque établissement."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{schoolTypes.map((item,i)=><SchoolCard key={item.type} {...item} featured={i===0}/>)}</div></section>
  <section className="relative overflow-hidden bg-[#f6fbff] py-20 sm:py-28"><div className="absolute -left-32 top-20 h-80 w-80 rounded-full bg-cyan-100/60 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-[.72fr_1.28fr] lg:px-8"><div><span className="section-eyebrow">UN SEUL ESPACE</span><h2 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">Tout ce dont vous avez besoin,<br/><span className="text-blue-700">au même endroit.</span></h2><p className="mt-5 max-w-lg leading-7 text-slate-600">Une interface pensée pour réduire les tâches dispersées et donner à chaque acteur la bonne information au bon moment.</p><Link href="#fonctionnalites" className="mt-7 inline-flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 font-bold text-white shadow-xl">Voir les fonctionnalités <Arrow/></Link></div><Dashboard/></div></section>
  <section id="fonctionnalites" className="section-shell"><SectionTitle eyebrow="UNE PLATEFORME COMPLÈTE" title={<>Des outils qui <span className="text-blue-700">travaillent avec vous.</span></>} text="Les fonctions essentielles de la gestion scolaire, réunies dans une interface simple."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([icon,title,text])=><Feature key={title} icon={icon} title={title} text={text}/>)}</div></section>
  <section id="espaces" className="relative overflow-hidden bg-slate-950 py-20 text-white sm:py-28"><div className="absolute -right-32 -top-32 h-96 w-96 rounded-full bg-blue-600/30 blur-3xl"/><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionTitle dark eyebrow="UNE EXPÉRIENCE POUR CHACUN" title={<>Un espace adapté à <span className="text-cyan-300">chaque rôle.</span></>} text="Administration, enseignants, élèves et parents : chacun retrouve son quotidien au même endroit."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{spaces.map(([role,title,text])=><Space key={role} role={role} title={title} text={text}/>)}</div></div></section>
  <section className="section-shell"><SectionTitle eyebrow="UNE INTERFACE QUI DONNE ENVIE" title={<>Pensée pour être <span className="text-blue-700">belle et utile.</span></>} text="Des informations lisibles, des actions rapides et une expérience cohérente sur ordinateur comme sur mobile."/><div className="grid gap-6 lg:grid-cols-3"><Quote text="Une gestion beaucoup plus claire pour toute notre équipe." label="Direction d'établissement"/><Quote text="Je retrouve rapidement mes classes, mes présences et mes notes." label="Enseignant"/><Quote text="Les informations de mon enfant sont enfin faciles à suivre." label="Parent"/></div></section>
  <section className="relative overflow-hidden px-4 pb-20 sm:px-6 sm:pb-28 lg:px-8"><div className="relative mx-auto max-w-6xl overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-[#0b57d0] via-[#0878df] to-[#27d7e8] px-6 py-14 text-center text-white shadow-[0_30px_80px_rgba(11,87,208,.25)] sm:px-12 sm:py-20"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full border-[45px] border-white/10"/><div className="absolute -bottom-32 -left-10 h-64 w-64 rounded-full border-[35px] border-white/10"/><div className="relative"><span className="text-[11px] font-black tracking-[.22em] text-cyan-100">PRÊT À SIMPLIFIER VOTRE ÉCOLE ?</span><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Faites passer votre établissement<br className="hidden sm:block"/> à l'étape suivante.</h2><p className="mx-auto mt-5 max-w-xl text-blue-50/90">Commencez avec une expérience de gestion scolaire moderne et pensée pour votre quotidien.</p><Link href={primaryHref} className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-7 py-4 font-black text-blue-800 shadow-xl">{user?"Accéder à mon espace":"Commencer avec Schooly"}<Arrow/></Link></div></div></section>
 </>;
}

function SectionTitle({eyebrow,title,text,dark=false}:{eyebrow:string;title:React.ReactNode;text:string;dark?:boolean}){return <div className="mx-auto mb-12 max-w-3xl text-center"><span className={`text-[11px] font-black tracking-[.22em] ${dark?"text-cyan-300":"text-blue-700"}`}>{eyebrow}</span><h2 className={`mt-4 text-3xl font-black tracking-tight sm:text-5xl ${dark?"text-white":"text-slate-950"}`}>{title}</h2><p className={`mx-auto mt-5 max-w-2xl leading-7 ${dark?"text-slate-300":"text-slate-600"}`}>{text}</p></div>}
function Stat({value,label,icon}:{value:string;label:string;icon:string}){return <div className="flex items-center justify-center gap-3 px-2 py-4 text-center sm:py-5 lg:border-r lg:border-slate-100 lg:last:border-0"><span className="hidden h-10 w-10 items-center justify-center rounded-2xl bg-blue-50 text-blue-700 sm:flex">{icon}</span><div><p className="text-2xl font-black text-slate-950">{value}</p><p className="text-[10px] font-bold text-slate-500 sm:text-xs">{label}</p></div></div>}
function SchoolCard({type,accent,description,levels,featured}:{type:SchoolType;accent:string;description:string;levels:string[];featured?:boolean}){return <article className={`group relative overflow-hidden rounded-[1.7rem] border bg-white p-5 transition duration-300 hover:-translate-y-2 hover:shadow-2xl ${featured?"border-blue-200 shadow-lg shadow-blue-100":"border-slate-100 shadow-sm"}`}><div className={`flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br ${accent} text-2xl text-white shadow-lg`}>{SCHOOL_TYPE_ICONS[type]}</div><h3 className="mt-5 font-black text-slate-950">{SCHOOL_TYPE_LABELS[type]}</h3><p className="mt-3 min-h-[72px] text-sm leading-6 text-slate-500">{description}</p><div className="mt-4 flex flex-wrap gap-1.5">{levels.map(x=><span key={x} className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{x}</span>)}</div><div className="absolute -right-8 -top-8 h-20 w-20 rounded-full bg-blue-50 transition group-hover:scale-150"/></article>}
function Feature({icon,title,text}:{icon:string;title:string;text:string}){return <article className="group rounded-[1.7rem] border border-slate-100 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Icon name={icon}/><h3 className="mt-5 text-lg font-black text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p><div className="mt-6 h-1 w-8 rounded-full bg-cyan-400 transition-all group-hover:w-16"/></article>}
function Space({role,title,text}:{role:string;title:string;text:string}){return <article className="rounded-[1.7rem] border border-white/10 bg-white/[.06] p-6 backdrop-blur transition hover:-translate-y-1 hover:bg-white/[.1]"><Icon dark name={role}/><h3 className="mt-6 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{text}</p><span className="mt-6 inline-flex text-xs font-bold text-cyan-300">Découvrir →</span></article>}
function Quote({text,label}:{text:string;label:string}){return <article className="rounded-[1.7rem] border border-slate-100 bg-white p-7 shadow-sm"><div className="flex gap-1 text-amber-400">★★★★★</div><p className="mt-5 text-lg font-bold leading-7 text-slate-800">“{text}”</p><p className="mt-5 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p></article>}
function Icon({name,dark=false}:{name:string;dark?:boolean}){const map:Record<string,string>={students:"👥",teachers:"♟",grades:"▣",attendance:"✓",messages:"✦",calendar:"▦",admin:"⌘",teacher:"✎",student:"◆",parent:"♡"};return <span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${dark?"bg-white/10 text-cyan-200":"bg-blue-50 text-blue-700"} text-xl shadow-sm`}>{map[name]??"✦"}</span>}
function Arrow(){return <span aria-hidden>↗</span>}
function HeroScene(){return <div className="relative mx-auto h-full w-full max-w-[610px]"><div className="absolute right-0 top-6 h-[390px] w-[390px] rounded-full bg-white/10 blur-2xl lg:right-8 lg:top-16 lg:h-[450px] lg:w-[450px]"/><div className="absolute bottom-3 right-2 h-[330px] w-[330px] rounded-[44%_56%_58%_42%/55%_45%_55%_45%] bg-white/95 shadow-2xl shadow-blue-950/20 lg:right-12 lg:h-[440px] lg:w-[440px]"/><div className="absolute right-9 top-20 z-10 w-[300px] rounded-[2rem] border border-white/60 bg-white/95 p-4 shadow-2xl shadow-blue-950/20 sm:right-20 sm:w-[390px] lg:top-32"><div className="flex items-center justify-between"><div><div className="h-2 w-16 rounded-full bg-slate-200"/><div className="mt-2 h-4 w-28 rounded bg-slate-900"/></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[9px] font-black text-emerald-600">ACTIF</span></div><div className="mt-5 grid grid-cols-3 gap-2"><Mini label="Élèves" value="524"/><Mini label="Présents" value="96%"/><Mini label="Classes" value="24"/></div><div className="mt-4 h-28 rounded-2xl bg-gradient-to-br from-blue-50 to-cyan-50 p-3"><div className="flex h-full items-end gap-2">{[35,55,44,72,62,88,76].map((h,i)=><div key={i} className="flex-1 rounded-t-md bg-blue-500/70" style={{height:`${h}%`}}/>)}</div></div></div><div className="float-card absolute -left-5 top-32 z-20 rounded-2xl border border-white/70 bg-white p-4 shadow-xl sm:left-0"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-50 text-cyan-600">✓</span><div><p className="text-xs font-black text-slate-900">Présence</p><p className="text-[10px] text-slate-400">Aujourd'hui · 96%</p></div></div></div><div className="float-card-delay absolute -bottom-1 right-4 z-20 rounded-2xl border border-white/70 bg-white p-4 shadow-xl sm:right-0"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-500">★</span><div><p className="text-xs font-black text-slate-900">Notes</p><p className="text-[10px] text-slate-400">Bulletins prêts</p></div></div></div><div className="absolute bottom-5 left-6 z-10 hidden h-28 w-28 rounded-full bg-gradient-to-br from-cyan-300 to-blue-600 shadow-xl sm:block"/><div className="absolute right-[-6px] top-12 z-30 hidden h-14 w-14 items-center justify-center rounded-full bg-amber-400 text-xl shadow-lg sm:flex">✦</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-bold text-slate-400">{label}</p><p className="mt-1 text-base font-black text-slate-900">{value}</p></div>}
function Dashboard(){return <div className="relative rounded-[2.2rem] bg-slate-950 p-3 shadow-[0_35px_80px_rgba(2,8,23,.22)] sm:p-5"><div className="rounded-[1.6rem] bg-white p-4 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-blue-600">Tableau de bord</p><h3 className="mt-1 text-xl font-black text-slate-900">Bonjour, Direction 👋</h3></div><div className="h-10 w-10 rounded-full bg-blue-100"/></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Mini label="Élèves inscrits" value="524"/><Mini label="Présence" value="96%"/><Mini label="Paiements" value="84%"/></div><div className="mt-4 grid gap-4 md:grid-cols-[1.4fr_.8fr]"><div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="text-xs font-black text-slate-800">Évolution des effectifs</p><span className="text-[10px] font-bold text-slate-400">2026</span></div><div className="mt-5 flex h-36 items-end gap-2">{[40,48,42,62,57,72,66,86,76,92].map((h,i)=><div key={i} className="flex-1 rounded-t-lg bg-blue-600/80" style={{height:`${h}%`}}/>)}</div></div><div className="rounded-2xl bg-gradient-to-br from-blue-700 to-cyan-500 p-5 text-white"><p className="text-xs font-bold text-blue-100">À surveiller</p><p className="mt-2 text-4xl font-black">12</p><p className="mt-1 text-xs text-blue-50">élèves nécessitent un suivi</p><div className="mt-8 h-2 rounded-full bg-white/20"><div className="h-2 w-2/3 rounded-full bg-white"/></div></div></div></div></div>}
